# Generated by Django 2.1.1 on 2019-03-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoosuprightnow', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
