# Generated by Django 2.1.1 on 2019-03-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosuprightnow', '0003_remove_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AddField(
            model_name='profile',
            name='activity',
            field=models.CharField(default='', max_length=100),
        ),
    ]
